# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 21, 1538, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.filetype_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.filetype_comboBox.setFont(font)
        self.filetype_comboBox.setObjectName("filetype_comboBox")
        self.filetype_comboBox.addItem("")
        self.filetype_comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.filetype_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.plottype_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plottype_comboBox.setFont(font)
        self.plottype_comboBox.setObjectName("plottype_comboBox")
        self.plottype_comboBox.addItem("")
        self.plottype_comboBox.addItem("")
        self.plottype_comboBox.addItem("")
        self.plottype_comboBox.addItem("")
        self.verticalLayout.addWidget(self.plottype_comboBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.rawplot_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rawplot_comboBox.setFont(font)
        self.rawplot_comboBox.setObjectName("rawplot_comboBox")
        self.horizontalLayout_3.addWidget(self.rawplot_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.diagplot_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.diagplot_comboBox.setFont(font)
        self.diagplot_comboBox.setObjectName("diagplot_comboBox")
        self.horizontalLayout_2.addWidget(self.diagplot_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.overplot_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.overplot_comboBox.setFont(font)
        self.overplot_comboBox.setObjectName("overplot_comboBox")
        self.horizontalLayout.addWidget(self.overplot_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.autoplot_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.autoplot_checkBox.setFont(font)
        self.autoplot_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.autoplot_checkBox.setObjectName("autoplot_checkBox")
        self.verticalLayout.addWidget(self.autoplot_checkBox)
        self.plotButton = QtWidgets.QPushButton(self.layoutWidget)
        self.plotButton.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.plotButton.setFont(font)
        self.plotButton.setObjectName("plotButton")
        self.verticalLayout.addWidget(self.plotButton)
        self.horizontalLayout_32.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.xmin_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.xmin_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.xmin_SpinBox.setFont(font)
        self.xmin_SpinBox.setMinimum(-10.0)
        self.xmin_SpinBox.setMaximum(10.0)
        self.xmin_SpinBox.setProperty("value", -10.0)
        self.xmin_SpinBox.setObjectName("xmin_SpinBox")
        self.horizontalLayout_5.addWidget(self.xmin_SpinBox)
        self.xmin_hScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.xmin_hScrollBar.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.xmin_hScrollBar.setFont(font)
        self.xmin_hScrollBar.setMinimum(-10)
        self.xmin_hScrollBar.setMaximum(10)
        self.xmin_hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.xmin_hScrollBar.setObjectName("xmin_hScrollBar")
        self.horizontalLayout_5.addWidget(self.xmin_hScrollBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.xmax_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.xmax_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.xmax_SpinBox.setFont(font)
        self.xmax_SpinBox.setMinimum(-10.0)
        self.xmax_SpinBox.setMaximum(10.0)
        self.xmax_SpinBox.setProperty("value", 10.0)
        self.xmax_SpinBox.setObjectName("xmax_SpinBox")
        self.horizontalLayout_6.addWidget(self.xmax_SpinBox)
        self.xmax_hScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.xmax_hScrollBar.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.xmax_hScrollBar.setFont(font)
        self.xmax_hScrollBar.setMinimum(-10)
        self.xmax_hScrollBar.setMaximum(10)
        self.xmax_hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.xmax_hScrollBar.setObjectName("xmax_hScrollBar")
        self.horizontalLayout_6.addWidget(self.xmax_hScrollBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.ymin_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.ymin_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ymin_SpinBox.setFont(font)
        self.ymin_SpinBox.setMinimum(-10.0)
        self.ymin_SpinBox.setMaximum(10.0)
        self.ymin_SpinBox.setProperty("value", -10.0)
        self.ymin_SpinBox.setObjectName("ymin_SpinBox")
        self.horizontalLayout_7.addWidget(self.ymin_SpinBox)
        self.ymin_hScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.ymin_hScrollBar.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ymin_hScrollBar.setFont(font)
        self.ymin_hScrollBar.setMinimum(-10)
        self.ymin_hScrollBar.setMaximum(10)
        self.ymin_hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.ymin_hScrollBar.setObjectName("ymin_hScrollBar")
        self.horizontalLayout_7.addWidget(self.ymin_hScrollBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.ymax_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.ymax_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ymax_SpinBox.setFont(font)
        self.ymax_SpinBox.setMinimum(-10.0)
        self.ymax_SpinBox.setMaximum(10.0)
        self.ymax_SpinBox.setProperty("value", 10.0)
        self.ymax_SpinBox.setObjectName("ymax_SpinBox")
        self.horizontalLayout_8.addWidget(self.ymax_SpinBox)
        self.ymax_hScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.ymax_hScrollBar.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ymax_hScrollBar.setFont(font)
        self.ymax_hScrollBar.setMinimum(-10)
        self.ymax_hScrollBar.setMaximum(10)
        self.ymax_hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.ymax_hScrollBar.setObjectName("ymax_hScrollBar")
        self.horizontalLayout_8.addWidget(self.ymax_hScrollBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.zmin_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.zmin_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.zmin_SpinBox.setFont(font)
        self.zmin_SpinBox.setMinimum(-10.0)
        self.zmin_SpinBox.setMaximum(10.0)
        self.zmin_SpinBox.setProperty("value", -10.0)
        self.zmin_SpinBox.setObjectName("zmin_SpinBox")
        self.horizontalLayout_9.addWidget(self.zmin_SpinBox)
        self.zmin_hScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.zmin_hScrollBar.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.zmin_hScrollBar.setFont(font)
        self.zmin_hScrollBar.setMinimum(-10)
        self.zmin_hScrollBar.setMaximum(10)
        self.zmin_hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.zmin_hScrollBar.setObjectName("zmin_hScrollBar")
        self.horizontalLayout_9.addWidget(self.zmin_hScrollBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.zmax_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.zmax_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.zmax_SpinBox.setFont(font)
        self.zmax_SpinBox.setMinimum(-10.0)
        self.zmax_SpinBox.setMaximum(10.0)
        self.zmax_SpinBox.setProperty("value", 10.0)
        self.zmax_SpinBox.setObjectName("zmax_SpinBox")
        self.horizontalLayout_10.addWidget(self.zmax_SpinBox)
        self.zmax_hScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.zmax_hScrollBar.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.zmax_hScrollBar.setFont(font)
        self.zmax_hScrollBar.setMinimum(-10)
        self.zmax_hScrollBar.setMaximum(10)
        self.zmax_hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.zmax_hScrollBar.setObjectName("zmax_hScrollBar")
        self.horizontalLayout_10.addWidget(self.zmax_hScrollBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_14.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.xslice_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.xslice_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.xslice_SpinBox.setFont(font)
        self.xslice_SpinBox.setMinimum(-10.0)
        self.xslice_SpinBox.setMaximum(10.0)
        self.xslice_SpinBox.setProperty("value", 0.0)
        self.xslice_SpinBox.setObjectName("xslice_SpinBox")
        self.horizontalLayout_11.addWidget(self.xslice_SpinBox)
        self.xslice_hScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.xslice_hScrollBar.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.xslice_hScrollBar.setFont(font)
        self.xslice_hScrollBar.setMinimum(-10)
        self.xslice_hScrollBar.setMaximum(10)
        self.xslice_hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.xslice_hScrollBar.setObjectName("xslice_hScrollBar")
        self.horizontalLayout_11.addWidget(self.xslice_hScrollBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.yslice_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.yslice_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.yslice_SpinBox.setFont(font)
        self.yslice_SpinBox.setMinimum(-10.0)
        self.yslice_SpinBox.setMaximum(10.0)
        self.yslice_SpinBox.setProperty("value", 0.0)
        self.yslice_SpinBox.setObjectName("yslice_SpinBox")
        self.horizontalLayout_12.addWidget(self.yslice_SpinBox)
        self.yslice_hScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.yslice_hScrollBar.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.yslice_hScrollBar.setFont(font)
        self.yslice_hScrollBar.setMinimum(-10)
        self.yslice_hScrollBar.setMaximum(10)
        self.yslice_hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.yslice_hScrollBar.setObjectName("yslice_hScrollBar")
        self.horizontalLayout_12.addWidget(self.yslice_hScrollBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.zslice_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.zslice_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.zslice_SpinBox.setFont(font)
        self.zslice_SpinBox.setMinimum(-10.0)
        self.zslice_SpinBox.setMaximum(10.0)
        self.zslice_SpinBox.setProperty("value", 0.0)
        self.zslice_SpinBox.setObjectName("zslice_SpinBox")
        self.horizontalLayout_13.addWidget(self.zslice_SpinBox)
        self.zslice_hScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.zslice_hScrollBar.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.zslice_hScrollBar.setFont(font)
        self.zslice_hScrollBar.setMinimum(-10)
        self.zslice_hScrollBar.setMaximum(10)
        self.zslice_hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.zslice_hScrollBar.setObjectName("zslice_hScrollBar")
        self.horizontalLayout_13.addWidget(self.zslice_hScrollBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.plane_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.plane_comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.plane_comboBox.setFont(font)
        self.plane_comboBox.setObjectName("plane_comboBox")
        self.plane_comboBox.addItem("")
        self.plane_comboBox.addItem("")
        self.plane_comboBox.addItem("")
        self.horizontalLayout_18.addWidget(self.plane_comboBox)
        self.plane_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.plane_SpinBox.setMinimumSize(QtCore.QSize(100, 0))
        self.plane_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plane_SpinBox.setFont(font)
        self.plane_SpinBox.setMinimum(-50.0)
        self.plane_SpinBox.setMaximum(50.0)
        self.plane_SpinBox.setObjectName("plane_SpinBox")
        self.horizontalLayout_18.addWidget(self.plane_SpinBox)
        self.plane_hScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.plane_hScrollBar.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plane_hScrollBar.setFont(font)
        self.plane_hScrollBar.setMinimum(-10)
        self.plane_hScrollBar.setMaximum(10)
        self.plane_hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.plane_hScrollBar.setObjectName("plane_hScrollBar")
        self.horizontalLayout_18.addWidget(self.plane_hScrollBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_14.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.savejpg_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.savejpg_checkBox.setFont(font)
        self.savejpg_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.savejpg_checkBox.setObjectName("savejpg_checkBox")
        self.horizontalLayout_16.addWidget(self.savejpg_checkBox)
        self.start_animateButton = QtWidgets.QPushButton(self.layoutWidget)
        self.start_animateButton.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start_animateButton.setFont(font)
        self.start_animateButton.setObjectName("start_animateButton")
        self.horizontalLayout_16.addWidget(self.start_animateButton)
        self.stop_animateButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_animateButton.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stop_animateButton.setFont(font)
        self.stop_animateButton.setObjectName("stop_animateButton")
        self.horizontalLayout_16.addWidget(self.stop_animateButton)
        self.continue_animateButton = QtWidgets.QPushButton(self.layoutWidget)
        self.continue_animateButton.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.continue_animateButton.setFont(font)
        self.continue_animateButton.setObjectName("continue_animateButton")
        self.horizontalLayout_16.addWidget(self.continue_animateButton)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.cmap_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cmap_checkBox.setFont(font)
        self.cmap_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmap_checkBox.setObjectName("cmap_checkBox")
        self.horizontalLayout_20.addWidget(self.cmap_checkBox)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setEnabled(True)
        self.label_16.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_20.addWidget(self.label_16)
        self.cmap_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.cmap_LineEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cmap_LineEdit.setObjectName("cmap_LineEdit")
        self.horizontalLayout_20.addWidget(self.cmap_LineEdit)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_20)
        self.cbar_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbar_checkBox.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cbar_checkBox.setFont(font)
        self.cbar_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbar_checkBox.setObjectName("cbar_checkBox")
        self.horizontalLayout_15.addWidget(self.cbar_checkBox)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setEnabled(True)
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_15.addWidget(self.label_4)
        self.cbar_min_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.cbar_min_LineEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cbar_min_LineEdit.setObjectName("cbar_min_LineEdit")
        self.horizontalLayout_15.addWidget(self.cbar_min_LineEdit)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setEnabled(True)
        self.label_15.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.cbar_max_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.cbar_max_LineEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cbar_max_LineEdit.setObjectName("cbar_max_LineEdit")
        self.horizontalLayout_15.addWidget(self.cbar_max_LineEdit)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(0, 28))
        self.label_14.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.tframe_SpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.tframe_SpinBox.setMinimumSize(QtCore.QSize(100, 0))
        self.tframe_SpinBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tframe_SpinBox.setFont(font)
        self.tframe_SpinBox.setObjectName("tframe_SpinBox")
        self.horizontalLayout_17.addWidget(self.tframe_SpinBox)
        self.tframe_hSlider = QtWidgets.QSlider(self.layoutWidget)
        self.tframe_hSlider.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tframe_hSlider.setFont(font)
        self.tframe_hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tframe_hSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.tframe_hSlider.setObjectName("tframe_hSlider")
        self.horizontalLayout_17.addWidget(self.tframe_hSlider)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(1325, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_32.addLayout(self.verticalLayout_7)
        self.layoutWidget.raise_()
        self.cmap_checkBox.raise_()
        self.cmap_LineEdit.raise_()
        self.label_16.raise_()
        self.label_16.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1600, 27))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionClose_2 = QtWidgets.QAction(MainWindow)
        self.actionClose_2.setObjectName("actionClose_2")
        self.actionCtrl_W = QtWidgets.QAction(MainWindow)
        self.actionCtrl_W.setObjectName("actionCtrl_W")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionClose_2)
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "File Type"))
        self.filetype_comboBox.setItemText(0, _translate("MainWindow", "HDF5"))
        self.filetype_comboBox.setItemText(1, _translate("MainWindow", "gda"))
        self.plottype_comboBox.setItemText(0, _translate("MainWindow", "Contour"))
        self.plottype_comboBox.setItemText(1, _translate("MainWindow", "Contour+X-Average"))
        self.plottype_comboBox.setItemText(2, _translate("MainWindow", "Contour+Z-Slice"))
        self.plottype_comboBox.setItemText(3, _translate("MainWindow", "Contour+X-Slice"))
        self.label_2.setText(_translate("MainWindow", "Raw Plot"))
        self.label_5.setText(_translate("MainWindow", "Diagnostic Plot"))
        self.label_6.setText(_translate("MainWindow", "Overplot"))
        self.autoplot_checkBox.setText(_translate("MainWindow", "Auto Update Plot"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.label.setText(_translate("MainWindow", "X-Min"))
        self.label_7.setText(_translate("MainWindow", "X-Max"))
        self.label_8.setText(_translate("MainWindow", "Y-Min"))
        self.label_9.setText(_translate("MainWindow", "Y-Max"))
        self.label_10.setText(_translate("MainWindow", "Z-Min"))
        self.label_11.setText(_translate("MainWindow", "Z-Max"))
        self.label_12.setText(_translate("MainWindow", "X-Slice"))
        self.label_17.setText(_translate("MainWindow", "Y-Slice"))
        self.label_13.setText(_translate("MainWindow", "Z-Slice"))
        self.plane_comboBox.setItemText(0, _translate("MainWindow", "X-Plane"))
        self.plane_comboBox.setItemText(1, _translate("MainWindow", "Y-Plane"))
        self.plane_comboBox.setItemText(2, _translate("MainWindow", "Z-Plane"))
        self.savejpg_checkBox.setText(_translate("MainWindow", "SAVE JPEGs"))
        self.start_animateButton.setText(_translate("MainWindow", "Start Animation"))
        self.stop_animateButton.setText(_translate("MainWindow", "Stop Animation"))
        self.continue_animateButton.setText(_translate("MainWindow", "Continue Animation"))
        self.cmap_checkBox.setText(_translate("MainWindow", "Fix Colormap"))
        self.label_16.setText(_translate("MainWindow", "cmap: "))
        self.cbar_checkBox.setText(_translate("MainWindow", "Fix Colorbar Range"))
        self.label_4.setText(_translate("MainWindow", "Min: "))
        self.label_15.setText(_translate("MainWindow", "Max: "))
        self.label_14.setText(_translate("MainWindow", "Time Slice"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionClose_2.setText(_translate("MainWindow", "Close"))
        self.actionClose_2.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionCtrl_W.setText(_translate("MainWindow", "Ctrl+W"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

